In [1]:
import numpy as np
import pandas as pd 

from scipy import stats

import seaborn as sns
import matplotlib.pyplot as plt
df= {
"procedural programming language":['c++','java','pascal','fortran#','et...'],
"functional programming language":['haskell','sml','scala','f#','etc...'],
"object oriented programming language":['c++','java','python','visual basic net','etc...'],
"scripting programming language":['javascript','php','perl','ruby','etc...'],
"logic programming language":['prolog','datalog','absys','alf','etc...'],
}
print(df)

{'procedural programming language': ['c++', 'java', 'pascal', 'fortran#', 'et...'], 'functional programming language': ['haskell', 'sml', 'scala', 'f#', 'etc...'], 'object oriented programming language': ['c++', 'java', 'python', 'visual basic net', 'etc...'], 'scripting programming language': ['javascript', 'php', 'perl', 'ruby', 'etc...'], 'logic programming language': ['prolog', 'datalog', 'absys', 'alf', 'etc...']}

In [4]:
df=pd.DataFrame(data=df)
df

,procedural programming language,functional programming language,object oriented programming language,scripting programming language,logic programming language
0,c++,haskell,c++,javascript,prolog
1,java,sml,java,php,datalog
2,pascal,scala,python,perl,absys
3,fortran#,f#,visual basic net,ruby,alf
4,et...,etc...,etc...,etc...,etc...

In [5]:
df.info

<bound method DataFrame.info of   procedural programming language functional programming language  \
0                             c++                         haskell
1                            java                             sml
2                          pascal                           scala
3                        fortran#                              f#
4                           et...                          etc...

  object oriented programming language scripting programming language  \
0                                  c++                     javascript
1                                 java                            php
2                               python                           perl
3                     visual basic net                           ruby
4                               etc...                         etc...

  logic programming language
0                     prolog
1                    datalog
2                      absys
3                        alf
4                     etc...  >

In [6]:
df.shape

(5, 5)

In [9]:
binary_encoded=pd.get_dummies(df,columns=['procedural programming language'])
binary_encoded

,functional programming language,object oriented programming language,scripting programming language,logic programming language,procedural programming language_c++,procedural programming language_et...,procedural programming language_fortran#,procedural programming language_java,procedural programming language_pascal
0,haskell,c++,javascript,prolog,1,0,0,0,0
1,sml,java,php,datalog,0,0,0,1,0
2,scala,python,perl,absys,0,0,0,0,1
3,f#,visual basic net,ruby,alf,0,0,1,0,0
4,etc...,etc...,etc...,etc...,0,1,0,0,0

In [10]:
binary_encoded=pd.get_dummies(df,columns=['functional programming language'])
binary_encoded

,procedural programming language,object oriented programming language,scripting programming language,logic programming language,functional programming language_etc...,functional programming language_f#,functional programming language_haskell,functional programming language_scala,functional programming language_sml
0,c++,c++,javascript,prolog,0,0,1,0,0
1,java,java,php,datalog,0,0,0,0,1
2,pascal,python,perl,absys,0,0,0,1,0
3,fortran#,visual basic net,ruby,alf,0,1,0,0,0
4,et...,etc...,etc...,etc...,1,0,0,0,0

In [11]:
binary_encoded=pd.get_dummies(df,columns=['object oriented programming language'])
binary_encoded

,procedural programming language,functional programming language,scripting programming language,logic programming language,object oriented programming language_c++,object oriented programming language_etc...,object oriented programming language_java,object oriented programming language_python,object oriented programming language_visual basic net
0,c++,haskell,javascript,prolog,1,0,0,0,0
1,java,sml,php,datalog,0,0,1,0,0
2,pascal,scala,perl,absys,0,0,0,1,0
3,fortran#,f#,ruby,alf,0,0,0,0,1
4,et...,etc...,etc...,etc...,0,1,0,0,0

In [12]:
binary_encoded=pd.get_dummies(df,columns=['scripting programming language'])
binary_encoded

,procedural programming language,functional programming language,object oriented programming language,logic programming language,scripting programming language_etc...,scripting programming language_javascript,scripting programming language_perl,scripting programming language_php,scripting programming language_ruby
0,c++,haskell,c++,prolog,0,1,0,0,0
1,java,sml,java,datalog,0,0,0,1,0
2,pascal,scala,python,absys,0,0,1,0,0
3,fortran#,f#,visual basic net,alf,0,0,0,0,1
4,et...,etc...,etc...,etc...,1,0,0,0,0

In [13]:
binary_encoded=pd.get_dummies(df,columns=['logic programming language'])
binary_encoded

,procedural programming language,functional programming language,object oriented programming language,scripting programming language,logic programming language_absys,logic programming language_alf,logic programming language_datalog,logic programming language_etc...,logic programming language_prolog
0,c++,haskell,c++,javascript,0,0,0,0,1
1,java,sml,java,php,0,0,1,0,0
2,pascal,scala,python,perl,1,0,0,0,0
3,fortran#,f#,visual basic net,ruby,0,1,0,0,0
4,et...,etc...,etc...,etc...,0,0,0,1,0

In [14]:
df['procedural programming language']=df['procedural programming language'].astype('category')
df.dtypes

procedural programming language         category
functional programming language           object
object oriented programming language      object
scripting programming language            object
logic programming language                object
dtype: object

In [15]:
df['functional programming language']=df['functional programming language'].astype('category')
df.dtypes

procedural programming language         category
functional programming language         category
object oriented programming language      object
scripting programming language            object
logic programming language                object
dtype: object

In [16]:
df['object oriented programming language']=df['object oriented programming language'].astype('category')
df.dtypes

procedural programming language         category
functional programming language         category
object oriented programming language    category
scripting programming language            object
logic programming language                object
dtype: object

In [17]:
df['scripting programming language']=df['scripting programming language'].astype('category')
df.dtypes

procedural programming language         category
functional programming language         category
object oriented programming language    category
scripting programming language          category
logic programming language                object
dtype: object

In [18]:
df['logic programming language']=df['logic programming language'].astype('category')
df.dtypes

procedural programming language         category
functional programming language         category
object oriented programming language    category
scripting programming language          category
logic programming language              category
dtype: object

In [19]:
from sklearn.preprocessing import OneHotEncoder

In [20]:
df['new_pro']=df['procedural programming language'].cat.codes
df['new_fun']=df['functional programming language'].cat.codes
df['new_obj']=df['object oriented programming language'].cat.codes
df['new_scr']=df['scripting programming language'].cat.codes
df['new_log']=df['logic programming language'].cat.codes
df

,procedural programming language,functional programming language,object oriented programming language,scripting programming language,logic programming language,new_pro,new_fun,new_obj,new_scr,new_log
0,c++,haskell,c++,javascript,prolog,0,2,0,1,4
1,java,sml,java,php,datalog,3,4,2,3,2
2,pascal,scala,python,perl,absys,4,3,3,2,0
3,fortran#,f#,visual basic net,ruby,alf,2,1,4,4,1
4,et...,etc...,etc...,etc...,etc...,1,0,1,0,3

In [23]:
enc=OneHotEncoder()

In [24]:
enc_df=pd.DataFrame(enc.fit_transform(df[['new_pro']]).toarray())
enc_df

     0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  1.0  0.0
2  0.0  0.0  0.0  0.0  1.0
3  0.0  0.0  1.0  0.0  0.0
4  0.0  1.0  0.0  0.0  0.0

In [25]:
new_df=df.join(enc_df)
new_df

,procedural programming language,functional programming language,object oriented programming language,scripting programming language,logic programming language,new_pro,new_fun,new_obj,new_scr,new_log,0,1,2,3,4
0,c++,haskell,c++,javascript,prolog,0,2,0,1,4,1.0,0.0,0.0,0.0,0.0
1,java,sml,java,php,datalog,3,4,2,3,2,0.0,0.0,0.0,1.0,0.0
2,pascal,scala,python,perl,absys,4,3,3,2,0,0.0,0.0,0.0,0.0,1.0
3,fortran#,f#,visual basic net,ruby,alf,2,1,4,4,1,0.0,0.0,1.0,0.0,0.0
4,et...,etc...,etc...,etc...,etc...,1,0,1,0,3,0.0,1.0,0.0,0.0,0.0